---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: foundation
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  interval: 10m0s
  path: ./local/foundation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: foundation
  interval: 10m0s
  path: ./local/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 10m0s
  path: ./local/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster
  interval: 10m0s
  path: ./local/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
