---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m0s
  path: ./components/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system