---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: selfsigned-cluster-issuer
  namespace: cert-manager
spec:
  interval: 10m0s
  path: ./components/cert-manager/cluster-local-issuer
  targetNamespace: cert-manager
  prune: true
  wait: true
  dependsOn:
  - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system