---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prom-stack
spec:
  chart:
    spec:
      chart: prom-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
      version: '>= 58.0.0'
  interval: 1m0s
  values:
    installCRDs: true
