---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: trust-manager
spec:
  chart:
    spec:
      chart: trust-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: '>= 0.9.2'
  interval: 1m0s
