---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 10m0s
  path: ./components/linkerd/control-plane
  targetNamespace: linkerd
  wait: true
  prune: true
  dependsOn:
  - name: linkerd-crds
  - name: linkerd-trust-anchor
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system