---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  interval: 10m0s
  path: ./components/linkerd/crds
  targetNamespace: linkerd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system