---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  interval: 10m0s
  path: ./components/linkerd/identity-issuer
  targetNamespace: linkerd
  prune: true
  wait: true
  dependsOn:
  - name: linkerd-trust-anchor
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system