apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
  namespace: cert-manager
spec:
  sources:
  - secret:
      name: linkerd-root-ca
      key: "tls.crt"
  target:
    configMap:
      key: "ca.crt"
    namespaceSelector:
      matchLabels:
        root.linkerd.io/trust: 'true'
        