---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prom-stack
  namespace: prom-stack
spec:
  interval: 10m0s
  path: ./components/prom-stack
  targetNamespace: prom-stack
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system